name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: devkitpro/devkita64
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: zip
      run: sudo apt install zip && zip -r Plugin.zip 010005F00E036000
    - uses: actions/upload-artifact@v2
      with:
        name: Plugin
        path: Plugin.zip
